STATUS_FEED_STATE_REVIEW_REJECTED = "review_rejected"
STATUS_FEED_STATE_PENDING_ENTRY = "pending_entry"
STATUS_FEED_STATE_POSITION_ENTRY = "position_entry"
STATUS_FEED_STATE_POSITION_CLOSED = "position_closed"
STATUS_FEED_STATE_NO_SETUP = "no_setup"
ACTIVE_HEARTBEAT_EVENT_TYPES = frozenset({"pending_entry_active", "position_entry_active"})
SHORT_STATUS_FEED_TRANSITION_SECONDS = 300

QUALIFYING_STATUS_STATES = {
    STATUS_FEED_STATE_REVIEW_REJECTED,
    STATUS_FEED_STATE_PENDING_ENTRY,
    STATUS_FEED_STATE_POSITION_ENTRY,
    STATUS_FEED_STATE_POSITION_CLOSED,
    STATUS_FEED_STATE_NO_SETUP,
}

SCHEDULED_REFRESH_STATUS_STATES = {
    STATUS_FEED_STATE_PENDING_ENTRY,
    STATUS_FEED_STATE_POSITION_ENTRY,
    STATUS_FEED_STATE_NO_SETUP,
}
