const baseSubscriberAccountCopy = {
  ko: {
    title: "알림 및 계정 설정",
    subtitle: "관심 AI 트레이더의 상세 알림 조건과 Telegram 연동 채널을 한 곳에서 모니터링하고 제어합니다.",
    active: "활성 구독",
    favorites: "모니터링 대상 AI 트레이더",
    favoritesHint: "알림을 수신하려는 전략 데스크를 선택하세요. 아무것도 선택하지 않으면 모든 트레이더의 신호가 전송됩니다.",
    alerts: "Telegram 연동",
    alertsHint: "전체 알림을 기본으로 받고, AI 중간 리뷰는 중요도와 본문 구성까지 세부 조절합니다.",
    enabled: "실시간 알림 수신 중",
    disabled: "알림 일시 중지됨",
    chatId: "Telegram Chat ID",
    minReturnPct: "최소 청산 수익률 필터",
    saved: "자동 저장됨",
    saving: "설정 저장 중...",
    saveFailed: "저장 실패",
    noFavorites: "선택된 트레이더 없음 (전체 활성화)",
    signaled: "송출 대기 중",
    statusConnected: "연결 활성화",
    statusDisconnected: "연결 비활성화",
    telegramSettingsLabel: "텔레그램 전송 매개변수",
    allTradersActive: "선택된 트레이더가 없어 전체 트레이더의 알림을 수신합니다.",
    activeTradersActive: "아래 선택된 트레이더의 알림만 수신합니다.",
    monitoredScope: "알림 대상",
    eventChannels: "이벤트 채널",
    reviewContent: "리뷰 본문",
    minReturnPctHelp: "수익률 절대값이 이 기준(%) 이상인 익절/손절 이벤트만 전송됩니다. 0% 설정 시 모든 청산 알림 수신.",
    telegramConnectTitle: "Telegram 계정 연결",
    telegramConnectedTitle: "Telegram 연결됨",
    telegramConnectedChat: "연결된 Chat ID",
    telegramConnectHelp: "Chat ID 입력은 필요 없습니다. 버튼으로 Telegram을 열고 봇 대화에서 시작을 누른 뒤 이 화면으로 돌아와 연결 확인을 눌러주세요.",
    telegramConnect: "Telegram 연결하기",
    telegramReconnect: "다시 연결하기",
    telegramConnecting: "링크 생성 중",
    telegramRefresh: "연결 확인",
    telegramRefreshing: "확인 중",
    telegramConnectOpened: "Telegram에서 봇 시작 후 이 화면으로 돌아와 연결 확인을 눌러주세요.",
    telegramLinkFailed: "연결 링크를 만들지 못했습니다. 서버 Telegram 봇 설정을 확인하세요.",
    telegramOpenFallback: "Telegram 링크 다시 열기",
    alertsOn: "Alerts On",
    alertsOff: "Alerts Off",
    selectedCount: "명 선택됨",
    eventGroupLabel: "알림 세부 항목",
    eventLabels: {
      pending_entry: "진입대기",
      position_entry: "진입완료",
      take_profit: "익절완료",
      stop_loss: "손절완료",
      ai_review_low: "AI 리뷰 낮음",
      ai_review_medium: "AI 리뷰 중간",
      ai_review_high: "AI 리뷰 높음",
      risk: "리스크 경보",
    },
    eventDescriptions: {
      pending_entry: "2차 AI 승인 후 실제 종이 주문이 대기 상태가 됨",
      position_entry: "대기 주문이 체결되어 포지션이 열린 상태",
      take_profit: "목표가 도달 또는 수익 보호로 익절 완료",
      stop_loss: "손절가 도달 또는 논리 무효화로 손절 완료",
      ai_review_low: "일반 점검성 중간 리뷰",
      ai_review_medium: "주의가 필요한 보유/대기 상태 리뷰",
      ai_review_high: "즉시 확인할 만한 방어적 리뷰",
      risk: "주문 거절, 비정상 리스크, 레버리지 경고"
    },
    reviewSectionGroupLabel: "AI 리뷰 메시지 구성",
    reviewSectionLabels: {
      status: "상태",
      position: "포지션",
      summary: "요약",
      action: "지금 할 일",
      key_reasons: "핵심 이유",
      risks: "주의할 점",
      watch_conditions: "다음 확인 조건",
      manager_note: "관리 메모",
      rationale: "판단 근거"
    },
    reviewSectionDescriptions: {
      status: "단계, 판단, 조치, 신뢰도",
      position: "방향, 진입가, 현재가, 손절/익절, PnL",
      summary: "AI가 내린 결론과 한 줄 상황 요약",
      action: "지금 당장 해야 할 관리 행동",
      key_reasons: "판단을 지지하는 주요 근거",
      risks: "주의해야 할 반대 신호와 위험",
      watch_conditions: "다음 캔들에서 확인할 조건",
      manager_note: "관리 관점의 보충 메모",
      rationale: "짧은 판단 근거 원문"
    },
    readiness: {
      disabled: "알림이 비활성화되어 있습니다.",
      missing_server_token: "서버 Telegram API 토큰이 설정되지 않았습니다.",
      missing_chat_id: "Telegram 계정을 먼저 연결해 주세요.",
      missing_event_types: "수신할 알림 카테고리를 하나 이상 선택하세요.",
      ready: "Telegram 연동 채널이 정상 활성화되었습니다."
    }
  },
  en: {
    title: "Alerts & Account Settings",
    subtitle: "Monitor and control real-time alert filters and Telegram integration for your favorite AI traders.",
    active: "Active Subscription",
    favorites: "Monitored AI Traders",
    favoritesHint: "Select strategy desks to receive alerts. If none are selected, alerts for all traders will be dispatched by default.",
    alerts: "Telegram Integration",
    alertsHint: "Receive all alerts by default, then tune AI management reviews by importance and message content.",
    enabled: "Alerts Active",
    disabled: "Alerts Paused",
    chatId: "Telegram Chat ID",
    minReturnPct: "Minimum Exit Return Filter",
    saved: "Settings Saved",
    saving: "Saving changes...",
    saveFailed: "Save failed",
    noFavorites: "All Traders Active",
    signaled: "Ready to Stream",
    statusConnected: "Connection Active",
    statusDisconnected: "Connection Inactive",
    telegramSettingsLabel: "Telegram Configuration",
    allTradersActive: "No traders selected. Streaming alerts for all traders.",
    activeTradersActive: "Streaming alerts only for the selected traders below.",
    monitoredScope: "Alert scope",
    eventChannels: "Event channels",
    reviewContent: "Review content",
    minReturnPctHelp: "Only take-profit or stop-loss events with an absolute return greater than or equal to this threshold (%) will be delivered. Set to 0% to receive all.",
    telegramConnectTitle: "Connect Telegram Account",
    telegramConnectedTitle: "Telegram Connected",
    telegramConnectedChat: "Connected Chat ID",
    telegramConnectHelp: "No Chat ID entry is needed. Open Telegram from this button, start the bot, then return here and check the connection.",
    telegramConnect: "Connect Telegram",
    telegramReconnect: "Reconnect",
    telegramConnecting: "Creating link",
    telegramRefresh: "Check connection",
    telegramRefreshing: "Checking",
    telegramConnectOpened: "Start the bot in Telegram, then return here and check the connection.",
    telegramLinkFailed: "Could not create a connection link. Check the server Telegram bot setup.",
    telegramOpenFallback: "Open Telegram link again",
    alertsOn: "Alerts On",
    alertsOff: "Alerts Off",
    selectedCount: "selected",
    eventGroupLabel: "Alert detail",
    eventLabels: {
      pending_entry: "Entry Pending",
      position_entry: "Entry Filled",
      take_profit: "Take Profit",
      stop_loss: "Stop Loss",
      ai_review_low: "AI Review Low",
      ai_review_medium: "AI Review Medium",
      ai_review_high: "AI Review High",
      risk: "Risk Alert",
    },
    eventDescriptions: {
      pending_entry: "Second-stage AI approval created a live paper order",
      position_entry: "A pending order filled and opened a paper position",
      take_profit: "Target or profit-protection exit completed",
      stop_loss: "Stop loss or thesis-failure exit completed",
      ai_review_low: "Routine management review",
      ai_review_medium: "Management review worth watching",
      ai_review_high: "Defensive management review that deserves attention",
      risk: "Order rejection, abnormal risk, or leverage warning"
    },
    reviewSectionGroupLabel: "AI review message content",
    reviewSectionLabels: {
      status: "Status",
      position: "Position",
      summary: "Summary",
      action: "Next action",
      key_reasons: "Key reasons",
      risks: "Risks",
      watch_conditions: "Watch next",
      manager_note: "Manager note",
      rationale: "Reason"
    },
    reviewSectionDescriptions: {
      status: "Phase, decision, action, and confidence",
      position: "Side, entry, current price, stop, target, and PnL",
      summary: "AI conclusion and one-line situation summary",
      action: "The immediate management action to take",
      key_reasons: "Main evidence supporting the decision",
      risks: "Counter-signals and risk points to watch",
      watch_conditions: "Conditions to check on upcoming candles",
      manager_note: "Extra management context",
      rationale: "Short raw decision rationale"
    },
    readiness: {
      disabled: "Alerts are currently turned off.",
      missing_server_token: "Server Telegram bot token is missing.",
      missing_chat_id: "Connect your Telegram account first.",
      missing_event_types: "Select at least one event category to monitor.",
      ready: "Telegram notification channel is successfully connected."
    }
  }
} as const;

export const SUBSCRIBER_ACCOUNT_COPY = {
  ...baseSubscriberAccountCopy,
  ru: {
    ...baseSubscriberAccountCopy.en,
    title: "Уведомления и настройки аккаунта",
    subtitle: "Управляйте Telegram-каналом и условиями уведомлений для выбранных AI-трейдеров.",
    active: "Активная подписка",
    favorites: "AI-трейдеры для мониторинга",
    favoritesHint: "Выберите стратегии для уведомлений. Если ничего не выбрано, будут приходить сигналы всех трейдеров.",
    alerts: "Интеграция Telegram",
    alertsHint: "Базовые события включены по умолчанию, а AI-обзоры можно настроить по важности и составу сообщения.",
    enabled: "Уведомления активны",
    disabled: "Уведомления на паузе",
    saved: "Сохранено",
    saving: "Сохраняем...",
    saveFailed: "Не удалось сохранить",
    noFavorites: "Все трейдеры активны",
    telegramConnectTitle: "Подключить Telegram",
    telegramConnectedTitle: "Telegram подключен",
    telegramConnect: "Подключить Telegram",
    telegramReconnect: "Подключить заново",
    telegramRefresh: "Проверить подключение",
    alertsOn: "Alerts On",
    alertsOff: "Alerts Off",
    selectedCount: "выбрано",
    eventLabels: {
      pending_entry: "Ожидает входа",
      position_entry: "Вход исполнен",
      take_profit: "Тейк-профит",
      stop_loss: "Стоп-лосс",
      ai_review_low: "AI-обзор низкий",
      ai_review_medium: "AI-обзор средний",
      ai_review_high: "AI-обзор высокий",
      risk: "Риск"
    },
    reviewSectionLabels: {
      status: "Статус",
      position: "Позиция",
      summary: "Итог",
      action: "Что сделать",
      key_reasons: "Причины",
      risks: "Риски",
      watch_conditions: "Условия",
      manager_note: "Заметка",
      rationale: "Основание"
    }
  },
  "pt-BR": {
    ...baseSubscriberAccountCopy.en,
    title: "Alertas e configurações da conta",
    subtitle: "Controle em um só lugar os filtros de alerta e a integração Telegram dos seus AI traders favoritos.",
    active: "Assinatura ativa",
    favorites: "AI traders monitorados",
    favoritesHint: "Selecione as mesas de estratégia para receber alertas. Sem seleção, todos os traders são enviados.",
    alerts: "Integração Telegram",
    alertsHint: "Eventos principais ficam ativados por padrão, e revisões AI podem ser ajustadas por importância e conteúdo.",
    enabled: "Alertas ativos",
    disabled: "Alertas pausados",
    saved: "Salvo",
    saving: "Salvando...",
    saveFailed: "Falha ao salvar",
    noFavorites: "Todos os traders ativos",
    telegramConnectTitle: "Conectar Telegram",
    telegramConnectedTitle: "Telegram conectado",
    telegramConnect: "Conectar Telegram",
    telegramReconnect: "Reconectar",
    telegramRefresh: "Verificar conexão",
    alertsOn: "Alerts On",
    alertsOff: "Alerts Off",
    selectedCount: "selecionados",
    eventLabels: {
      pending_entry: "Entrada pendente",
      position_entry: "Entrada executada",
      take_profit: "Take profit",
      stop_loss: "Stop loss",
      ai_review_low: "Revisão AI baixa",
      ai_review_medium: "Revisão AI média",
      ai_review_high: "Revisão AI alta",
      risk: "Risco"
    },
    reviewSectionLabels: {
      status: "Status",
      position: "Posição",
      summary: "Resumo",
      action: "Próxima ação",
      key_reasons: "Motivos",
      risks: "Riscos",
      watch_conditions: "Condições",
      manager_note: "Nota",
      rationale: "Motivo"
    }
  },
  tr: {
    ...baseSubscriberAccountCopy.en,
    title: "Bildirimler ve hesap ayarları",
    subtitle: "Favori AI traderlarınızın Telegram bağlantısını ve bildirim koşullarını tek yerden yönetin.",
    active: "Aktif abonelik",
    favorites: "İzlenen AI traderlar",
    favoritesHint: "Bildirim almak istediğiniz strateji masalarını seçin. Seçim yoksa tüm trader sinyalleri gönderilir.",
    alerts: "Telegram bağlantısı",
    alertsHint: "Ana olaylar varsayılan olarak gelir; AI ara incelemelerini önem ve içerik bazında ayarlayabilirsiniz.",
    enabled: "Bildirimler aktif",
    disabled: "Bildirimler duraklatıldı",
    saved: "Kaydedildi",
    saving: "Kaydediliyor...",
    saveFailed: "Kaydetme başarısız",
    noFavorites: "Tüm traderlar aktif",
    telegramConnectTitle: "Telegram bağla",
    telegramConnectedTitle: "Telegram bağlı",
    telegramConnect: "Telegram bağla",
    telegramReconnect: "Yeniden bağla",
    telegramRefresh: "Bağlantıyı kontrol et",
    alertsOn: "Alerts On",
    alertsOff: "Alerts Off",
    selectedCount: "seçildi",
    eventLabels: {
      pending_entry: "Giriş bekliyor",
      position_entry: "Giriş tamamlandı",
      take_profit: "Kar alındı",
      stop_loss: "Zarar kesildi",
      ai_review_low: "AI inceleme düşük",
      ai_review_medium: "AI inceleme orta",
      ai_review_high: "AI inceleme yüksek",
      risk: "Risk"
    },
    reviewSectionLabels: {
      status: "Durum",
      position: "Pozisyon",
      summary: "Özet",
      action: "Aksiyon",
      key_reasons: "Nedenler",
      risks: "Riskler",
      watch_conditions: "Koşullar",
      manager_note: "Not",
      rationale: "Gerekçe"
    }
  }
} as const;
