import type { CanonicalBlogPost } from "@/lib/blog/types";

export const canonicalBasePosts: readonly CanonicalBlogPost[] = [
  { slug: "ai-trader-league", category: "TRADING", publishedAt: "2026-07-10", modifiedAt: "2026-07-12", sourceIds: ["cfa", "sec-backtest"], relatedSlugs: ["ai-trading-leaderboard", "ai-strategy-comparison", "why-simulation-matters"] },
  { slug: "ai-trading-leaderboard", category: "GUIDE", publishedAt: "2026-07-09", modifiedAt: "2026-07-12", sourceIds: ["cfa", "sec-backtest"], relatedSlugs: ["trader-profile-reading", "monthly-league-recap", "r-multiple-expectancy"] },
  { slug: "btc-futures-ai-sentiment", category: "MARKET", publishedAt: "2026-07-08", modifiedAt: "2026-07-12", sourceIds: ["cftc", "cme"], relatedSlugs: ["crypto-funding-rates", "open-interest-explained", "mark-index-last-price"] },
  { slug: "paper-trading-vs-live-trading", category: "RISK", publishedAt: "2026-07-07", modifiedAt: "2026-07-12", sourceIds: ["sec-backtest", "cfa"], relatedSlugs: ["why-simulation-matters", "trading-costs-backtests", "slippage-partial-fills"] },
  { slug: "telegram-trading-alerts", category: "ALERTS", publishedAt: "2026-07-06", modifiedAt: "2026-07-13", sourceIds: ["telegram-bot-api", "investor-gov"], relatedSlugs: ["risk-review-before-entry", "stop-loss-execution-risk", "crypto-phishing-fake-support"] },
  { slug: "risk-review-before-entry", category: "RISK", publishedAt: "2026-07-05", modifiedAt: "2026-07-12", sourceIds: ["cftc", "cme"], relatedSlugs: ["position-sizing-risk-budget", "stop-loss-execution-risk", "margin-vs-risk-budget"] },
  { slug: "ai-strategy-comparison", category: "STRATEGY", publishedAt: "2026-07-04", modifiedAt: "2026-07-12", sourceIds: ["cfa", "nber-ta"], relatedSlugs: ["trend-analysis-basics", "walk-forward-testing", "monthly-league-recap"] },
  { slug: "monthly-league-recap", category: "RECAP", publishedAt: "2026-07-03", modifiedAt: "2026-07-12", sourceIds: ["cfa", "sec-backtest"], relatedSlugs: ["ai-trading-leaderboard", "trading-journal-audit", "drawdown-loss-streak-risk"] },
  { slug: "trader-profile-reading", category: "GUIDE", publishedAt: "2026-07-02", modifiedAt: "2026-07-12", sourceIds: ["cfa", "cme"], relatedSlugs: ["ai-trading-leaderboard", "position-sizing-risk-budget", "r-multiple-expectancy"] },
  { slug: "why-simulation-matters", category: "RESEARCH", publishedAt: "2026-07-01", modifiedAt: "2026-07-12", sourceIds: ["sec-backtest", "cfa"], relatedSlugs: ["paper-trading-vs-live-trading", "crypto-backtest-data-quality", "lookahead-survivorship-bias"] },
];

const groups = {
  bitcoin: ["bitcoin-utxo-model", "bitcoin-mining-proof-of-work", "bitcoin-halving-supply-schedule", "bitcoin-difficulty-adjustment", "bitcoin-mempool-fees", "bitcoin-confirmations-reorg-risk", "bitcoin-private-keys-addresses", "bitcoin-full-node-validation", "bitcoin-lightning-network-basics"],
  execution: ["market-vs-limit-orders", "stop-vs-stop-limit-orders", "bid-ask-spread", "order-book-depth-liquidity", "maker-taker-fees", "slippage-partial-fills", "volume-vs-liquidity"],
  risk: ["position-sizing-risk-budget", "r-multiple-expectancy", "stop-loss-execution-risk", "drawdown-loss-streak-risk", "margin-vs-risk-budget", "trading-journal-audit", "overtrading-costs"],
  technical: ["trend-analysis-basics", "support-resistance-zones", "moving-average-lag", "rsi-explained", "macd-explained", "atr-volatility", "bollinger-bands", "multi-timeframe-analysis"],
  derivatives: ["futures-vs-perpetuals", "crypto-funding-rates", "leverage-margin-liquidation", "mark-index-last-price", "futures-basis-contango-backwardation", "open-interest-explained"],
  operations: ["crypto-transfer-network-memo-basics"],
  research: ["crypto-backtest-data-quality", "lookahead-survivorship-bias", "walk-forward-testing", "trading-costs-backtests", "sharpe-ratio-limitations"],
  security: ["seed-phrase-security", "hot-wallet-vs-hardware-wallet", "crypto-phishing-fake-support", "address-poisoning-scams", "token-approvals-wallet-permissions", "blockchain-bridge-risks", "stablecoin-proof-of-reserves"],
} as const;

const related: Readonly<Record<string, readonly [string, string, string]>> = {
  "bitcoin-utxo-model": ["bitcoin-private-keys-addresses", "bitcoin-mempool-fees", "bitcoin-full-node-validation"],
  "bitcoin-mining-proof-of-work": ["bitcoin-difficulty-adjustment", "bitcoin-halving-supply-schedule", "bitcoin-full-node-validation"],
  "bitcoin-halving-supply-schedule": ["bitcoin-mining-proof-of-work", "bitcoin-difficulty-adjustment", "futures-basis-contango-backwardation"],
  "bitcoin-difficulty-adjustment": ["bitcoin-mining-proof-of-work", "bitcoin-confirmations-reorg-risk", "bitcoin-full-node-validation"],
  "bitcoin-mempool-fees": ["bitcoin-utxo-model", "bitcoin-confirmations-reorg-risk", "bitcoin-lightning-network-basics"],
  "bitcoin-confirmations-reorg-risk": ["bitcoin-full-node-validation", "bitcoin-mining-proof-of-work", "crypto-transfer-network-memo-basics"],
  "bitcoin-private-keys-addresses": ["seed-phrase-security", "hot-wallet-vs-hardware-wallet", "bitcoin-utxo-model"],
  "bitcoin-full-node-validation": ["bitcoin-confirmations-reorg-risk", "bitcoin-mining-proof-of-work", "bitcoin-utxo-model"],
  "bitcoin-lightning-network-basics": ["bitcoin-mempool-fees", "bitcoin-confirmations-reorg-risk", "blockchain-bridge-risks"],
  "market-vs-limit-orders": ["maker-taker-fees", "slippage-partial-fills", "order-book-depth-liquidity"],
  "stop-vs-stop-limit-orders": ["stop-loss-execution-risk", "slippage-partial-fills", "market-vs-limit-orders"],
  "bid-ask-spread": ["order-book-depth-liquidity", "volume-vs-liquidity", "slippage-partial-fills"],
  "order-book-depth-liquidity": ["bid-ask-spread", "volume-vs-liquidity", "slippage-partial-fills"],
  "maker-taker-fees": ["market-vs-limit-orders", "trading-costs-backtests", "overtrading-costs"],
  "slippage-partial-fills": ["order-book-depth-liquidity", "market-vs-limit-orders", "stop-loss-execution-risk"],
  "volume-vs-liquidity": ["bid-ask-spread", "order-book-depth-liquidity", "slippage-partial-fills"],
  "position-sizing-risk-budget": ["margin-vs-risk-budget", "r-multiple-expectancy", "drawdown-loss-streak-risk"],
  "r-multiple-expectancy": ["position-sizing-risk-budget", "trading-journal-audit", "sharpe-ratio-limitations"],
  "stop-loss-execution-risk": ["stop-vs-stop-limit-orders", "slippage-partial-fills", "position-sizing-risk-budget"],
  "drawdown-loss-streak-risk": ["position-sizing-risk-budget", "margin-vs-risk-budget", "r-multiple-expectancy"],
  "margin-vs-risk-budget": ["leverage-margin-liquidation", "position-sizing-risk-budget", "drawdown-loss-streak-risk"],
  "trading-journal-audit": ["r-multiple-expectancy", "overtrading-costs", "walk-forward-testing"],
  "overtrading-costs": ["trading-journal-audit", "maker-taker-fees", "trading-costs-backtests"],
  "trend-analysis-basics": ["moving-average-lag", "support-resistance-zones", "multi-timeframe-analysis"],
  "support-resistance-zones": ["trend-analysis-basics", "atr-volatility", "multi-timeframe-analysis"],
  "moving-average-lag": ["trend-analysis-basics", "macd-explained", "multi-timeframe-analysis"],
  "rsi-explained": ["macd-explained", "bollinger-bands", "multi-timeframe-analysis"],
  "macd-explained": ["moving-average-lag", "rsi-explained", "trend-analysis-basics"],
  "atr-volatility": ["bollinger-bands", "support-resistance-zones", "position-sizing-risk-budget"],
  "bollinger-bands": ["atr-volatility", "rsi-explained", "moving-average-lag"],
  "multi-timeframe-analysis": ["trend-analysis-basics", "support-resistance-zones", "lookahead-survivorship-bias"],
  "futures-vs-perpetuals": ["crypto-funding-rates", "futures-basis-contango-backwardation", "mark-index-last-price"],
  "crypto-funding-rates": ["futures-vs-perpetuals", "open-interest-explained", "futures-basis-contango-backwardation"],
  "leverage-margin-liquidation": ["margin-vs-risk-budget", "mark-index-last-price", "stop-loss-execution-risk"],
  "mark-index-last-price": ["leverage-margin-liquidation", "futures-vs-perpetuals", "open-interest-explained"],
  "futures-basis-contango-backwardation": ["futures-vs-perpetuals", "crypto-funding-rates", "open-interest-explained"],
  "open-interest-explained": ["crypto-funding-rates", "futures-basis-contango-backwardation", "volume-vs-liquidity"],
  "crypto-backtest-data-quality": ["lookahead-survivorship-bias", "trading-costs-backtests", "walk-forward-testing"],
  "lookahead-survivorship-bias": ["crypto-backtest-data-quality", "walk-forward-testing", "multi-timeframe-analysis"],
  "walk-forward-testing": ["lookahead-survivorship-bias", "crypto-backtest-data-quality", "sharpe-ratio-limitations"],
  "trading-costs-backtests": ["crypto-backtest-data-quality", "slippage-partial-fills", "maker-taker-fees"],
  "sharpe-ratio-limitations": ["walk-forward-testing", "r-multiple-expectancy", "drawdown-loss-streak-risk"],
  "crypto-transfer-network-memo-basics": ["bitcoin-confirmations-reorg-risk", "address-poisoning-scams", "crypto-phishing-fake-support"],
  "seed-phrase-security": ["hot-wallet-vs-hardware-wallet", "crypto-phishing-fake-support", "bitcoin-private-keys-addresses"],
  "hot-wallet-vs-hardware-wallet": ["seed-phrase-security", "token-approvals-wallet-permissions", "crypto-phishing-fake-support"],
  "crypto-phishing-fake-support": ["seed-phrase-security", "address-poisoning-scams", "token-approvals-wallet-permissions"],
  "address-poisoning-scams": ["crypto-transfer-network-memo-basics", "crypto-phishing-fake-support", "token-approvals-wallet-permissions"],
  "token-approvals-wallet-permissions": ["crypto-phishing-fake-support", "hot-wallet-vs-hardware-wallet", "blockchain-bridge-risks"],
  "blockchain-bridge-risks": ["token-approvals-wallet-permissions", "stablecoin-proof-of-reserves", "hot-wallet-vs-hardware-wallet"],
  "stablecoin-proof-of-reserves": ["blockchain-bridge-risks", "hot-wallet-vs-hardware-wallet", "crypto-backtest-data-quality"],
};

const sourceOverrides: Readonly<Record<string, readonly [string, string, ...string[]]>> = {
  "bitcoin-utxo-model": ["bitcoin-dev", "bitcoin-core"],
  "bitcoin-mining-proof-of-work": ["bitcoin-paper", "bitcoin-core", "bitcoin-dev"],
  "bitcoin-halving-supply-schedule": ["bitcoin-core", "bitcoin-dev", "ap-bitcoin"],
  "bitcoin-difficulty-adjustment": ["bitcoin-core", "bitcoin-dev"],
  "bitcoin-mempool-fees": ["bitcoin-core", "bitcoin-dev"],
  "bitcoin-confirmations-reorg-risk": ["bitcoin-paper", "bitcoin-dev"],
  "bitcoin-private-keys-addresses": ["bitcoin-paper", "bitcoin-dev", "bip32", "bip173", "bip350"],
  "bitcoin-full-node-validation": ["bitcoin-core", "bitcoin-dev"],
  "bitcoin-lightning-network-basics": ["lightning", "bitcoin-dev"],
  "market-vs-limit-orders": ["investor-gov", "coinbase-orders"],
  "stop-vs-stop-limit-orders": ["investor-gov", "finra", "coinbase-orders"],
  "bid-ask-spread": ["cme", "coinbase-market-data"],
  "order-book-depth-liquidity": ["cme", "coinbase-market-data"],
  "maker-taker-fees": ["coinbase-orders", "kraken-orders"],
  "slippage-partial-fills": ["investor-gov", "coinbase-orders"],
  "volume-vs-liquidity": ["cme", "coinbase-market-data"],
  "position-sizing-risk-budget": ["cme", "cftc"],
  "r-multiple-expectancy": ["cme", "cfa"],
  "stop-loss-execution-risk": ["finra", "coinbase-orders"],
  "drawdown-loss-streak-risk": ["sec-backtest", "cfa"],
  "margin-vs-risk-budget": ["investor-gov", "finra", "cftc"],
  "trading-journal-audit": ["cme", "pardo"],
  "overtrading-costs": ["finra", "sec-backtest"],
  "trend-analysis-basics": ["cme", "nber-ta"],
  "support-resistance-zones": ["cme", "nyfed-support"],
  "moving-average-lag": ["talib", "tradingview-indicators"],
  "rsi-explained": ["talib", "tradingview-indicators"],
  "macd-explained": ["talib", "tradingview-indicators"],
  "atr-volatility": ["talib", "tradingview-indicators"],
  "bollinger-bands": ["bollinger", "tradingview-indicators"],
  "multi-timeframe-analysis": ["cfa", "tradingview-indicators"],
  "futures-vs-perpetuals": ["cme", "kraken-futures"],
  "crypto-funding-rates": ["coinbase-funding", "kraken-futures"],
  "leverage-margin-liquidation": ["cftc", "kraken-futures"],
  "mark-index-last-price": ["kraken-futures", "cftc"],
  "futures-basis-contango-backwardation": ["cme", "cftc"],
  "open-interest-explained": ["cftc", "cme"],
  "crypto-transfer-network-memo-basics": ["bitcoin-dev", "coinbase-transfers"],
  "crypto-backtest-data-quality": ["kaiko", "coinbase-market-data"],
  "lookahead-survivorship-bias": ["cfa", "sec-backtest"],
  "walk-forward-testing": ["cfa", "sec-backtest"],
  "trading-costs-backtests": ["cfa", "coinbase-fees", "kraken-fees"],
  "sharpe-ratio-limitations": ["cfa", "sec-backtest"],
  "seed-phrase-security": ["ledger", "trezor", "cisa"],
  "hot-wallet-vs-hardware-wallet": ["ledger", "trezor", "sec-custody"],
  "crypto-phishing-fake-support": ["ftc", "fbi", "cisa", "korean-fsc"],
  "address-poisoning-scams": ["metamask", "ledger"],
  "token-approvals-wallet-permissions": ["eip20", "eip721", "eip1155", "eip2612", "ethereum-security"],
  "blockchain-bridge-risks": ["ethereum-bridges", "fsb"],
  "stablecoin-proof-of-reserves": ["fsb", "pcaob"],
};

function buildGroup(
  category: string,
  slugs: readonly string[],
): readonly CanonicalBlogPost[] {
  return slugs.map((slug) => {
    const sourceIds = sourceOverrides[slug];
    if (!sourceIds) throw new Error(`Missing topic-specific sources: ${slug}`);
    return {
      slug,
      category: category.toUpperCase(),
      publishedAt: "2026-07-12",
      modifiedAt: "2026-07-12",
      sourceIds,
      relatedSlugs: related[slug],
    };
  });
}

export const canonicalBlogAdditions: readonly CanonicalBlogPost[] = [
  ...buildGroup("bitcoin", groups.bitcoin),
  ...buildGroup("execution", groups.execution),
  ...buildGroup("risk", groups.risk),
  ...buildGroup("technical-analysis", groups.technical),
  ...buildGroup("derivatives", groups.derivatives),
  ...buildGroup("operations", groups.operations),
  ...buildGroup("backtesting", groups.research),
  ...buildGroup("security", groups.security),
];
